dashboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views


app_name='dashboard'
urlpatterns = [
    path('', views.HomeView.as_view(), name='Home'),
    path('notes/', views.notesAdd, name='Notes'),
    path('homework/', views.HomeworkFormView, name='Home_work'),
    path('todo/', views.todo, name='todo'),
    path('youtube/', views.youtube, name='youtube'),
    path('books/', views.books, name='books'),
    path('dictionary/', views.dictionary, name='dictionary'),
    path('wiki/', views.wiki, name='wiki'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('notes-delete/<int:pk>/', views.deletenote, name='Notes_delete'),
    path('notes-detail/<int:pk>/', views.NoteDetailView.as_view(), name='Notes_detail'),
    path('homework-update/<int:pk>/', views.update_homework, name='homework_update'),
    path('homework-delete/<int:pk>/', views.delete_homework, name='homework_delete'),
    path('todo-delete/<int:pk>/', views.todo_delete, name='todo_delete'),
    path('todo-update/<int:pk>/', views.update_todo, name='todo_update'),
    path('login/', LoginView.as_view(), name='Login'),
    path('logout/', LogoutView.as_view(), name='Logout')
]

studentPortal/urls.py
from django.contrib import admin
from django.urls import path,include

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
     url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

dashboard/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Notes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()

    class Meta:
        verbose_name = "notes"
        verbose_name_plural = "notes"

    def __str__(self):
        return self.title

class Homework(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    description = models.TextField()
    due = models.DateTimeField()
    is_finished = models.BooleanField(default=False)

    def __str__(self):
        return self.subject

class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    is_finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
User = get_user_model()

from .models import *

class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['title', 'description']

class DateInput(forms.DateInput):
    input_type = 'date'

class HomeworkForm(forms.ModelForm):
    class Meta:
        model = Homework
        widgets = {'due': DateInput()}
        fields = ['subject', 'title', 'description', 'due', 'is_finished']

class DashboardForm(forms.Form):
    text = forms.CharField(max_length=100, label="Enter Your Search :")

class TodoForm(forms.ModelForm):
    class Meta:
        model =Todo
        fields = ['title', 'is_finished']

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username']

dashboard/views.py
import requests
from django.contrib import messages
from django.shortcuts import render,reverse,redirect
import wikipedia
# Create your views here.
from django.views.generic import *
from .forms import NotesForm, HomeworkForm, DashboardForm, TodoForm, UserRegistrationForm
from .models import Notes, Homework, Todo
from youtubesearchpython import VideosSearch


class HomeView(ListView):
    template_name = "dashboard/home.html"

    def get_queryset(self):
        pass

def notesAdd(request):
    if request.method == "POST":
        form = NotesForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            user = request.user
            notes = Notes.objects.create(user=user, title=title, description=description)
            notes.save()
            messages.success(request, f"Notes Added Successfully from {request.user.username}")
            return redirect("dashboard:Notes")
    else:
        form = NotesForm()
    notes = Notes.objects.filter(user=request.user)
    context = {
        'form' : form,
        'notes': notes,
    }
    return render(request, 'dashboard/notes.html', context)

def deletenote(request, pk=None):
    note = Notes.objects.get(id=pk)
    note.delete()
    return redirect("dashboard:Notes")

class NoteDetailView(DetailView):
    model = Notes

def HomeworkFormView(request):
    if request.method == "POST":
        form = HomeworkForm(request.POST)
        if form.is_valid():
            try:
                finished = request.POST['is_finished']
                if finished == 'on':
                    finished = True
                else:
                    finished = False
            except:
                finished = False
            subject = request.POST['subject']
            title = request.POST['title']
            description = request.POST['description']
            due = request.POST['due']
            is_finished = finished
            homework = Homework.objects.create(user=request.user, subject=subject, title=title, description=description,
                                               due=due, is_finished=is_finished)
            homework.save()
            messages.success(request, f"Homework Added Successfully from {request.user.username}")
            return redirect("dashboard:Home_work")
    else:
        form = HomeworkForm()
    homeworks = Homework.objects.filter(user=request.user)
    context ={
        'form' : form,
        'homeworks' : homeworks
    }
    return render(request, 'dashboard/homework.html', context)

def update_homework(request, pk=None):
    homework = Homework.objects.get(id=pk)
    if homework.is_finished == True:
        homework.is_finished = False
    else:
        homework.is_finished = True
    homework.save()
    return redirect("dashboard:Home_work")

def delete_homework(requeat, pk=None):
    homework = Homework.objects.get(id=pk)
    homework.delete()
    return redirect("dashboard:Home_work")

def youtube(request):
    if request.method == "POST":
        form = DashboardForm(request.POST)
        text = request.POST['text']
        video = VideosSearch(text,limit=10)
        result_list = []
        for i in video.result()['result']:
            result_dict = {
                'input': text,
                'title': i['title'],
                'duration': i['duration'],
                'thumbnail': i['thumbnails'][0]['url'],
                'channel': i['channel']['name'],
                'link': i['link'],
                'views': i['viewCount']['short'],
                'published': i['publishedTime'],

            }
            desc = ''
            if i['descriptionSnippet']:
                for j in i['descriptionSnippet']:
                    desc += j['text']
            result_dict['description'] = desc
            result_list.append(result_dict)
            context = {
                'form' : form,
                'results': result_list
            }
        return render(request, 'dashboard/youtube.html',context)
    else:
        form = DashboardForm()
    context = {
        'form': form
    }
    return render(request, "dashboard/youtube.html",context)

def todo(request):
    if request.method == "POST":
        form = TodoForm(request.POST)
        if form.is_valid():
            try:
                finished = request.POST['is_finished']
                if finished == 'on':
                    finished = True
                else:
                    finished = False
            except:
                finished = False
            todos = Todo.objects.create(
                user=request.user,
                title=request.POST['title'],
                is_finished=finished
            )
            todos.save()
            messages.success(request, f"Todo Added from {request.user.username}" )
    else:
        form = TodoForm()
    todo = Todo.objects.filter(user=request.user)
    context = {
        'todos': todo,
        'form': form,
    }

    return render(request, "dashboard/todo.html", context)

def todo_delete(request, pk=None):
    todo = Todo.objects.get(id=pk)
    todo.delete()
    return redirect('dashboard:todo')

def update_todo(request, pk=None):
    todo = Todo.objects.get(id=pk)
    if todo.is_finished == True:
        todo.is_finished = False
    else:
        todo.is_finished = True
    todo.save()
    return redirect("dashboard:todo")

def books(request):
    if request.method == "POST":
        form = DashboardForm(request.POST)
        text = request.POST['text']
        url = "https://www.googleapis.com/books/v1/volumes?q="+text
        r = requests.get(url)
        answer = r.json()
        result_list = []
        for i in range(10):
            result_dict = {
                'title': answer['items'][i]['volumeInfo']['title'],
                'subtitle': answer['items'][i]['volumeInfo'].get('subtitle'),
                'description': answer['items'][i]['volumeInfo'].get('description'),
                'count': answer['items'][i]['volumeInfo'].get('count'),
                'categories': answer['items'][i]['volumeInfo'].get('categories'),
                'rating': answer['items'][i]['volumeInfo'].get('pageRating'),
                'thumbnail': answer['items'][i]['volumeInfo'].get('imageLinks').get('thumbnail'),
                'preview': answer['items'][i]['volumeInfo'].get('previewLink')
            }

            result_list.append(result_dict)
            context = {
                'form' : form,
                'results': result_list
            }
        return render(request, 'dashboard/books.html',context)
    else:
        form = DashboardForm()
    context = {
        'form': form
    }
    return render(request, 'dashboard/books.html',context)

def dictionary(request):
    if request.method == "POST":
        form = DashboardForm(request.POST)
        text = request.POST['text']
        url = "https://api.dictionaryapi.dev/api/v2/entries/en_US/"+text
        r = requests.get(url)
        answer = r.json()
        result_list = []
        try:
            phonetics = answer[0]['phonetics'][0]['text']
            audio = answer[0]['phonetics'][0]['audio']
            definition = answer[0]['meanings'][0]['definitions'][0]['definition']
            example = answer[0]['meanings'][0]['definitions'][0]['example']
            synonyms = answer[0]['meanings'][0]['definitions'][0]['synonyms']

            context = {
                'form' : form,
                'input': text,
                'phonetics' : phonetics,
                'definition' : definition,
                'example': example,
                'synonyms': synonyms,
                'audio': audio,
            }
        except:
            context = {
                'form': form,
                'input': ''
            }
        return render(request, 'dashboard/dictionary.html', context)
    else:
        form = DashboardForm()
        context={'form' : form}
    return render(request, 'dashboard/dictionary.html', context)

def wiki(request):
    if request.method == "POST":
        text = request.POST['text']
        form = DashboardForm(request.POST)
        search = wikipedia.page(text)

        context = {
            'form': form,
            'title': search.title,
            'link': search.links,
            'details': search.summary
        }
        return render(request, 'dashboard/wiki.html', context)
    else:
        form = DashboardForm()
        context = {
            'form': form
        }
    return render(request, 'dashboard/wiki.html',context)


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Account Created Successfully for {username}")
            return redirect('dashboard:Home')
    else:
        form = UserRegistrationForm()
    context = {
        'form': form
    }
    return render(request, 'dashboard/register.html', context)


def profile(request):
    homeworks = Homework.objects.filter(is_finished=False, user=request.user)
    todos = Todo.objects.filter(is_finished=False, user=request.user)

    context = {
        'homeworks' : homeworks,
        'todos': todos
    }

    return render(request, 'dashboard/profile.html', context)

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Student-dashboard</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'dashboard:Home' %}">Student Study Portal</a>        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'dashboard:Home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:profile' %}">Profile</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Options
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'dashboard:books' %}">Books</a>
                <a class="dropdown-item" href="{% url 'dashboard:wiki' %}">Wikipedia</a>
                <div class="dropdown-divider"></div>

                <a class="dropdown-item" href="{% url 'dashboard:dictionary' %}">Dictionary</a>
                <a class="dropdown-item" href="{% url 'dashboard:youtube' %}">Youtube</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'dashboard:todo' %}">To-do</a>
                <a class="dropdown-item" href="{% url 'dashboard:Home_work' %}">Homework</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'dashboard:Notes' %}">Notes</a>
                <a class="dropdown-item" href="#">Conversion</a>
                <div class="dropdown-divider"></div>
              </div>
            </li>


            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:Logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'dashboard:Login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <br /><br />
  <main>

    {% if messages %}
      {% for msg in messages %}
        <div class="alert alert-{{msg.tags}}">{{msg}}</div>
      {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

  </main>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
</body>

</html>

dashboard/templates/dashboard/home.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block content %}

<section class="container text-center">
  <h3>Welcome</h3>

  <hr> <br>
  <div class="row">
    <div class="col-md-3">
      <a href="{% url 'dashboard:Notes' %}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/notes.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Notes
            </h5>
            Create Notes to refer them later. They are stored permanently until deleted
          </div>
        </div>
      </a>
    </div>

    <div class="col-md-3">
      <a href="{% url 'dashboard:Home_work' %}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/homework.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Homework
            </h5>
            Add homeworks and assign them deadlines. They will be displayed prioritised by deadlines
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-3">
      <a href="{% url 'dashboard:youtube' %}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/youtube.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Youtube
            </h5>
            Search Youtube and select your desired video to play it on youtube
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-3">
      <a href="{% url 'dashboard:todo' %}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/todo.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              To Do
            </h5>
            Add your to-do lists for your day and remove them as you finish
          </div>
        </div>
      </a>
    </div>
  </div>
  <br><br><br>
  <div class="row">
    <div class="col-md-3 ">
      <a href="{% url 'dashboard:books' %}">
        <div class="card mt-20">
          <img class="card-img-top" src="{% static 'images/books.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Books
            </h5>
            Browse books from a list of neatly organised book menu
          </div>
        </div>
      </a>
    </div>



    <div class="col-md-3">
      <a href="{% url 'dashboard:dictionary' %}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/dictionary.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Dictionary
            </h5>
            A vocabulary from a book is troubling you? No problem, enter the word, and the meaning will be displayed
            almost instantaneously.
          </div>
        </div>
      </a>
    </div>
    <div class="col-md-3">
      <a href="{% url 'dashboard:wiki' %}">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/wiki.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              WikiPedia
            </h5>
            Homework and Assignments? Search wikipedia to get fast results
          </div>
        </div>
      </a>
    </div>


    <div class="col-md-3">
      <a href="#">
        <div class="card">
          <img class="card-img-top" src="{% static 'images/conversion.jpg' %}" alt="Notes image">
          <div class="card-body">
            <h5 class="card-title ">
              Conversion
            </h5>
            Check out the conversion table, that helps you to convert measurements to more familiar ones of your choice.
          </div>
        </div>
      </a>
    </div>
  </div>


</section>
{% endblock content %}

dashboard/templates/dashboard/homework.html
{% extends 'dashboard/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <table class="table table-striped table-bordered table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Subject</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Due</th>
                <th scope="col">Status</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for homework in homeworks %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{homework.subject}}</td>
                <td>{{homework.title}}</td>
                <td>{{homework.description}}</td>
                <td>{{homework.due}}</td>

                <td>
                    <a href="{% url 'dashboard:homework_update' homework.id %}">
                        <div class="form-check">
                            {% if homework.is_finished == True %}
                            <input class="form-check-input" type="checkbox" value="" checked >
                            {% else %}
                            <input class="form-check-input" type="checkbox" value="">
                            {% endif %}
                            <label class="form-check-label text-light" for="flexCheckDefault">
                                Mark as Completed
                            </label>
                        </div>
                    </a>
                </td>
                <td><a href="{% url 'dashboard:homework_delete' homework.id %}"><i class="fa fa-trash fa-2x"></i></a></td>
            </tr>
            {% empty %}
            <h4>All homeworks are completed!! Create to have more!!</h4>
            {% endfor %}
        </tbody>
    </table>

</div>
<div class=" container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Homework</legend>
        </fieldset>
        {{ form|crispy }}
        <div class="form-group">
            <button href="" class="btn btn-outline-info" type="submit">
                Create
            </button>
        </div>
    </form>
</div>
{% endblock content %}

dashboard/templates/dashboard/notes.html
{% extends 'dashboard/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row">
        {% for note in notes %}
        <div class="col-md-3">
            <a href="{% url 'dashboard:Notes_detail' note.id %}">
                <div class="card">
                    <div class="card-header">{{note.title}}</div>
                    <div class="card-body">{{note.description|slice:"0:100"}}</div>
                    <div class="card-footer mt-auto "><a href="{% url 'dashboard:Notes_delete' note.id %}">
                        <i class="fa fa-trash fa-2x"></i></a>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
        <br><br>

    </div>
</div>
<br><br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Notes</legend>
        </fieldset>
        {{ form|crispy }}
        <div class="form-group">
            <button href="" class="btn btn-outline-info" type="submit">
                Create
            </button>
        </div>
    </form>
</div>

{% endblock content %}

dashboard/templates/dashboard/notes_detail.html
{% extends 'dashboard/base.html' %} 
{% load static %} 
{% block content %}

<section class='text-center container'>

    <div class="container">

        <div class="content-section p-0 mt-5">

            <div class="m-3">
                <h2>{{notes.title}}</h2>
            </div>

            <hr class="p-0 m-0">
            <p class="description m-5 p-5">
                {{notes.description}}
            </p>
            <hr>
        </div>

    </div>

</section>

{% endblock content %}

dashboard/templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load crispy_forms_tags%}
{% block content %}
<section class="text-center">
    {% if not todos_done %}
    <div class="container">
        <h2>Due ToDos</h2>
        <table class="table table-striped table-bordered table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for todo in todos %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{todo.title}}</td>
                    <td>
                        <a href="{% url 'dashboard:todo_update' todo.id %}">
                            <div class="form-check">
                                {% if todo.is_finished == True %}
                                <input class="form-check-input" type="checkbox" value="" checked>
                                {% else %}
                                <input class="form-check-input" type="checkbox" value="">
                                {% endif %}
                                <label class="form-check-label text-light" for="flexCheckDefault">
                                    Mark as Completed
                                </label>
                            </div>
                        </a>
                    </td>

                    <td><a href="{% url 'dashboard:todo_delete' todo.id %}"><i class="fa fa-trash fa-2x"></i></a></td>
                </tr>
                {% empty %}
            <h3>All To dos are completed!!!!</h3>

            </tbody>
            {% endfor %}
        </table>


    {% endif %}
        <a href="{% url 'dashboard:todo' %}" class="btn btn-danger">To Do</a>
        <br><br>
        {% if not homework_done %}
        <h2>Due Homeworks</h2>
        <table class="table table-striped table-bordered table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Subject</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Due</th>
                    <th scope="col">Status</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>.subject</td>
                    <td>title</td>
                    <td>description</td>
                    <td>due</td>

                    <td>

                        <a href="#">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="" checked id=2>
                                <label class="form-check-label text-light" for="flexCheckDefault">
                                    Mark as Completed
                                </label>
                            </div>
                        </a>
                    </td>
                    <td><a href="#"><i class="fa fa-trash fa-2x"></i></a></td>
                </tr>
            </tbody>
        </table>
        <h3>All To homeworks are completed!!!!</h3>

        <a href="#" class="btn btn-danger">Homeworks</a>
    </div>
    {% endif %}
</section>

{% endblock content %}

dashboard/templates/dashboard/todo.html
{% extends 'dashboard/base.html' %} 
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">

    <table class="table table-striped table-bordered table-hover table-dark">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Status</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
        {% for todo in todos %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{todo.title}}</td>
                <td>
                    <a href="{% url 'dashboard:todo_update' todo.id %}">
                        <div class="form-check">
                            {% if todo.is_finished == True %}
                            <input class="form-check-input" type="checkbox" value="" checked>
                            {% else %}
                            <input class="form-check-input" type="checkbox" value="" >
                            {% endif %}
                            <label class="form-check-label text-light" for="flexCheckDefault">
                                Mark as Completed
                            </label>
                        </div>
                    </a>
                </td>

                <td><a href="{% url 'dashboard:todo_delete' todo.id %}"><i class="fa fa-trash fa-2x"></i></a></td>
            </tr>
            {% empty %}
    <h4>All tasks have been done!! create to add more</h4>
    {% endfor %}
        </tbody>
    </table>

</div><br><br>
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Todo</legend>
            {{form|crispy}}
        </fieldset>
        <div class="form-group">
            <button href="" class="btn btn-outline-info" type="submit">
                Create
            </button>
        </div>
    </form>
</div>

{% endblock content %}